openapi: "3.0.3"
info:
  $ref: ./info.yaml
servers:
  - url: https://api.hokan.io/api/ext/v1/
tags:
  $ref: ./tags.yaml
paths:
  $ref: "./paths/index.yaml"
components:
  $ref: "./components/index.yaml"
