OAuth2: # <---- arbitrary name
  type: oauth2
  description: This API uses OAuth2
  flows:
    authorizationCode:
      scopes:
        customers:read: Read customer information
        customers:create: Create new customer
        customers:update: Modify customer information
