APIキー:
  type: apiKey
  in: header
  name: X-API-KEY
  description: |
    本APIを実行するにあたり、トークンをヘッダに付与しなければ実行ができません.

    トークンは、hokan設定画面の「トークン発行機能」から発行することができます。
    
    APIを実行するごとにヘッダにトークンを付与しなければ、不正なアクセスとみなされAPIの実行ができません。
  

OAuth2(Internal): # <---- arbitrary name
  type: oauth2
  description: |
    本APIは権限管理処理を実現するために、内部的にOAuth2のスキームで権限管理を行います.

    認証処理には上記のAPIキーを使用しますが、トークン発行時に事前にAPI権限を付与した上で発行しなければなりません.
    
    APIを実行する場合、必要な権限を持ったトークンを使用しなければ、権限不足のためエラーが発生します。
  flows:
    authorizationCode:
      authorizationUrl: N/A
      tokenUrl: N/A
      scopes:
        customers:read: Read customer information
        customers:create: Create new customer
        customers:update: Modify customer information
